export default [
  {
    id: 0,
    img: "/images/icon-work.svg",
    activity: "Work",
    WeeklyHours: "32hrs",
    WeeklyDate: "Last Week - 36hrs",
    DailyHours: "5hrs",
    DailyDate: "Yesterday - 7hrs",
    MonthlyHours: "103hrs",
    MonthlyDate: "Last Month - 128hrs",
    cardIcon: "/images/icon-ellipsis.svg",
  },
  {
    id: 1,
    img: "/images/icon-play.svg",
    activity: "Play",
    WeeklyHours: "10hrs",
    WeeklyDate: "Last Week - 8hrs",
    DailyHours: "1hrs",
    DailyDate: "Yesterday - 2hrs",
    MonthlyHours: "23hrs",
    MonthlyDate: "Last Month - 29hrs",
    cardIcon: "/images/icon-ellipsis.svg",
  },
  {
    id: 2,
    img: "/images/icon-study.svg",
    activity: "Study",
    WeeklyHours: "4hrs",
    WeeklyDate: "Last Week - 7hrs",
    DailyHours: "0hrs",
    DailyDate: "Yesterday - 1hrs",
    MonthlyHours: "13hrs",
    MonthlyDate: "Last Month - 19hrs",
    cardIcon: "/images/icon-ellipsis.svg",
  },
  {
    id: 3,
    img: "/images/icon-exercise.svg",
    activity: "Exercise",
    WeeklyHours: "4hrs",
    WeeklyDate: "Last Week - 5hrs",
    DailyHours: "1hrs",
    DailyDate: "Yesterday - 1hrs",
    MonthlyHours: "11hrs",
    MonthlyDate: "Last Month - 18hrs",
    cardIcon: "/images/icon-ellipsis.svg",
  },
  {
    id: 4,
    img: "/images/icon-social.svg",
    activity: "Social",
    WeeklyHours: "5hrs",
    WeeklyDate: "Last Week - 10hrs",
    DailyHours: "1hrs",
    DailyDate: "Yesterday - 3hrs",
    MonthlyHours: "21hrs",
    MonthlyDate: "Last Month - 23hrs",
    cardIcon: "/images/icon-ellipsis.svg",
  },
  {
    id: 5,
    img: "/images/icon-self-care.svg",
    activity: "Self Care",
    WeeklyHours: "2hrs",
    WeeklyDate: "Last Week - 2hrs",
    DailyHours: "0hrs",
    DailyDate: "Yesterday - 1hrs",
    MonthlyHours: "7hrs",
    MonthlyDate: "Last Month - 11hrs",
    cardIcon: "/images/icon-ellipsis.svg",
  },
];
