export default [
  {
    id: 0,
    img: "/images/icon-work.svg",
    activity: "Work",
    WeeklyHours: "32hrs",
    Weeklydate: "Last Week - 36hrs",
    DailyHours: "5hrs",
    DailyDate: "",
    MonthlyHours: "",
    MonthlyDate: "",
    cardIcon: "/images/icon-ellipsis.svg",
  },
  {
    id: 1,
    img: "/images/icon-play.svg",
    activity: "Play",
    WeeklyHours: "10hrs",
    Weeklydate: "Last Week - 8hrs",
    DailyHours: "",
    DailyDate: "",
    MonthlyHours: "",
    MonthlyDate: "",
    cardIcon: "/images/icon-ellipsis.svg",
  },
  {
    id: 2,
    img: "/images/icon-study.svg",
    activity: "Study",
    WeeklyHours: "4hrs",
    Weeklydate: "Last Week - 7hrs",
    DailyHours: "",
    DailyDate: "",
    MonthlyHours: "",
    MonthlyDate: "",
    cardIcon: "/images/icon-ellipsis.svg",
  },
  {
    id: 3,
    img: "/images/icon-exercise.svg",
    activity: "Exercise",
    WeeklyHours: "4hrs",
    Weeklydate: "Last Week - 5hrs",
    DailyHours: "",
    DailyDate: "",
    MonthlyHours: "",
    MonthlyDate: "",
    cardIcon: "/images/icon-ellipsis.svg",
  },
  {
    id: 4,
    img: "/images/icon-social.svg",
    activity: "Social",
    WeeklyHours: "5hrs",
    Weeklydate: "Last Week - 10hrs",
    DailyHours: "",
    DailyDate: "",
    MonthlyHours: "",
    MonthlyDate: "",
    cardIcon: "/images/icon-ellipsis.svg",
  },
  {
    id: 5,
    img: "/images/icon-self-care.svg",
    activity: "Self Care",
    WeeklyHours: "2hrs",
    Weeklydate: "Last Week - 2hrs",
    DailyHours: "",
    DailyDate: "",
    MonthlyHours: "",
    MonthlyDate: "",
    cardIcon: "/images/icon-ellipsis.svg",
  },
];
